/**
 * All user-facing strings live here (CLAUDE.md convention: no hardcoded UI
 * text). German-first; login and /instance are English (spec §8.3/§15.1).
 */
export const strings = {
  placeholder: {
    deploymentBaseline: "Lean — Deployment-Baseline (M0).",
  },
  login: {
    // English by design — invitation links travel across organizations.
    welcome: "Welcome",
    emailLabel: "Email address",
    continueWithEmail: "Continue with email",
    checkInbox: "Check your inbox",
    codeSentTo: (email: string) => `We sent a 6-digit code to ${email}.`,
    codeRequested:
      "If this address is registered, a code is on its way.",
    ssoEnforced:
      "This domain uses single sign-on. Please sign in with Microsoft.",
    invalidCode: "That code is invalid or has expired.",
    sendNewCode: "Send a new code",
    youAreIn: "You're in.",
    openLean: "Open Lean",
    or: "or",
    signInWithMicrosoft: "Sign in with Microsoft",
    invitationOnly: "Invitation-only — there is no public sign-up.",
    noMemberships:
      "You have no active memberships. Ask an administrator to invite you.",
    pickTenant: "Choose a workspace",
  },
  invitation: {
    subject: (tenantName: string) => `You've been invited to ${tenantName} on Lean`,
    body: (tenantName: string, url: string) =>
      `You have been invited to join ${tenantName} on Lean.\n\nSign in with this email address to get started:\n${url}\n\nInvitation-only — there is no public sign-up.`,
  },
  otpMail: {
    subject: "Your Lean sign-in code",
    body: (otp: string) =>
      `Your sign-in code is: ${otp}\n\nIt is valid for 10 minutes and can be used once.`,
  },
  shell: {
    myWork: "Meine Arbeit",
    searchHint: "Suchen ( / )",
    themeToggle: "Dunkel/Hell",
    switchTenant: "Arbeitsbereich wechseln",
    logout: "Abmelden",
    logoutEverywhere: "Überall abmelden",
  },
  glance: {
    emptyBranch: "Noch nichts hier…",
    notStarted: "noch nicht gestartet",
    branches: "Bereiche",
    depthHint: (branches: number, tasks: number) => {
      const parts: string[] = [];
      if (branches > 0) parts.push(`${branches} ${branches === 1 ? "Teilbereich" : "Teilbereiche"}`);
      parts.push(tasks === 0 ? "Noch keine Aufgaben" : `${tasks} ${tasks === 1 ? "Aufgabe" : "Aufgaben"}`);
      return parts.join(" · ");
    },
    legend: "Fortschritt · Blockiert · Alarm",
    sizeToggle: "Kartengröße umschalten",
  },
  status: {
    open: "offen",
    in_progress: "in Arbeit",
    blocked: "blockiert",
    done: "erledigt",
  } as Record<string, string>,
  alarm: {
    stagnant: "stagniert",
    due_soon: "bald fällig",
    overdue: "überfällig",
  } as Record<string, string>,
  branch: {
    subBranches: "Teilbereiche",
    tasks: "Aufgaben",
    filterAll: "Alle",
    filterBlocked: "Blockiert",
    filterAlarms: "Alarme",
    filteredEmpty: "Keine Aufgaben für diesen Filter.",
    empty: "Noch nichts hier…",
    firstTask: "+ Erste Aufgabe anlegen",
    newTask: "+ Aufgabe",
    newBranch: "+ Teilbereich",
    newTaskTitle: "Titel der neuen Aufgabe",
    newBranchTitle: "Name des neuen Teilbereichs",
    create: "Anlegen",
    skeletonTooltip: "Nur Pfad sichtbar — kein Mitglied dieses Bereichs",
    neverProgressed: "noch nie ⟳",
    lastProgress: (ago: string) => `⟳ ${ago}`,
  },
  task: {
    description: "Beschreibung",
    noDescription: "Noch keine Beschreibung…",
    infoStream: "Informationsstrom",
    infoEmpty: "Noch keine Informationen. Beiträge aus Teams und manuelle Notizen erscheinen hier.",
    sourceManual: "Manuell",
    sourceTeams: "Teams",
    sourceAi: "KI-Zusammenfassung",
    openThread: "Thread öffnen ↗",
    discussion: "Diskussion",
    commentPlaceholder: "Kommentar schreiben…",
    send: "Senden",
    activity: "Aktivität",
    responsible: "Verantwortlich",
    due: "Fällig",
    noDate: "kein Datum",
    statusLabel: "Status",
    percentLabel: "Fortschritt",
    blockedNote: "Blockiert unterdrückt den Stagnations-Alarm — das Problem ist sichtbar markiert.",
    doneLocked: "Erledigt — bei 100 % gesperrt. Zum Ändern Status zurücksetzen.",
    percentZeroConfirm: "Aktives Segment abwählen und Fortschritt auf 0 % setzen?",
    readOnlyTooltip: "Nur die verantwortliche Person kann dies ändern",
    time: "Zeit",
    timeTotal: "Gesamt",
    record: "Erfassen",
    recordedToday: "Heute erfasst:",
    ownEntries: "Deine Einträge",
    timePlaceholder: "z. B. 45m oder 1,5h",
    presets: ["15 m", "30 m", "1 h", "2 h", "4 h", "8 h"],
  },
  activity: {
    created: "Aufgabe erstellt",
    statusChanged: (from: string, to: string) => `Status geändert: ${from} → ${to}`,
    percentChanged: (from: number, to: number) => `Fortschritt geändert: ${from} % → ${to} %`,
    responsibleChanged: (from: string, to: string) => `Verantwortung übergeben: ${from} → ${to}`,
    timeLogged: (duration: string) => `Zeit erfasst: ${duration}`,
    timeCorrected: "Zeiteintrag korrigiert",
    updated: "Aufgabe bearbeitet",
    infoAdded: "Information hinzugefügt",
    infoHidden: "Information ausgeblendet",
    commentAdded: "Kommentar hinzugefügt",
    alarmRaised: (kind: string) => `Alarm ausgelöst: ${kind}`,
    alarmCleared: (kind: string) => `Alarm aufgehoben: ${kind}`,
    archived: "Archiviert",
    unarchived: "Archivierung aufgehoben",
    moved: "Verschoben",
    fallback: "Änderung",
  },
  myWork: {
    title: "Meine Arbeit",
    myAlarms: "Meine Alarme",
    noAlarms: "Keine Alarme — alles im grünen Bereich.",
    groups: {
      overdue: "Überfällig",
      due_soon: "Bald fällig",
      stagnant: "Stagniert",
      rest: "Weitere",
    } as Record<string, string>,
    empty: "Dir ist derzeit keine Aufgabe zugewiesen.",
  },
  search: {
    title: "Suche",
    placeholder: "Suchen ( / )",
    resultsFor: (q: string) => `Ergebnisse für „${q}"`,
    noResults: "Keine Treffer.",
    groups: {
      branch: "Bereiche",
      task: "Aufgaben",
      info: "Informationen",
      comment: "Kommentare",
    } as Record<string, string>,
    hint: "↑/↓ wählen · Enter öffnen · Esc zurück",
  },
  admin: {
    title: "Verwaltung",
    navLabel: "Verwaltung",
    members: "Mitglieder & Flags",
    colName: "Name",
    colEmail: "E-Mail",
    flagAdmin: "Tenant-Admin",
    flagHr: "HR",
    flagBranches: "Bereiche anlegen",
    invite: "Mitglied einladen",
    inviteEmail: "E-Mail-Adresse",
    inviteName: "Anzeigename (für neue Nutzer)",
    inviteSend: "Einladen",
    invited: (email: string) => `Einladung an ${email} gesendet.`,
    entra: "Entra-Tenant-Allowlist",
    entraHint:
      "Eine Entra-Tenant-ID (GUID) pro Zeile — nie „beliebige Microsoft-Konten“. Leer = kein SSO für diesen Arbeitsbereich.",
    save: "Speichern",
    saved: "Gespeichert.",
    alarms: "Alarm-Standardwerte",
    stagnationDays: "Stagnations-Alarm nach (Tagen)",
    settings: "Tenant-Einstellungen",
    skeletonProgress: "Skeleton-Pfade zeigen Fortschritt",
    move: "Verschieben-Werkzeug",
    moveSource: "Element",
    moveTarget: "Neuer übergeordneter Bereich",
    moveConfirm:
      "Verschieben berechnet die Fortschritte des alten und des neuen Astes neu. Fortfahren?",
    moveDo: "Verschieben",
    moved: "Verschoben — Fortschritte neu berechnet.",
    apiTokens: {
      title: "API-Tokens (canri)",
      hint: "Zugriffstoken für den canri-Crawler. Beim Erstellen wird das Token nur einmal angezeigt — sofort kopieren und sicher hinterlegen.",
      nameLabel: "Bezeichnung",
      namePlaceholder: "canri crawler",
      create: "Token erstellen",
      shownOnce: "Neues Token — wird nur jetzt angezeigt:",
      colName: "Bezeichnung",
      colPrefix: "Prefix",
      colCreated: "Erstellt",
      colLastUsed: "Zuletzt genutzt",
      never: "—",
      revoke: "Widerrufen",
      revokeConfirm: "Dieses Token widerrufen? Der Crawler kann sich damit nicht mehr verbinden.",
      empty: "Noch keine Tokens.",
    },
  },
  branchAlarms: {
    label: "Stagnations-Alarm",
    days: (n: number) => `${n} Tage`,
    tenantDefault: (n: number) => `Standard (${n} Tage)`,
    inherited: "Standard",
    save: "OK",
    clear: "Standard verwenden",
  },
  archive: {
    archive: "Archivieren",
    unarchive: "Archivierung aufheben",
    confirm:
      "Archivieren? Der Eintrag verschwindet aus Rollup, Alarmen und Standardansichten.",
    showArchived: "Archiviert anzeigen",
    hideArchived: "Archiviert ausblenden",
    chip: "archiviert",
  },
  // English by design (spec §15.1): plain instance-operator pages.
  instance: {
    title: "Instance administration",
    tenants: "Tenants",
    createTenant: "Create tenant",
    slug: "Slug",
    name: "Name",
    create: "Create",
    appointAdmin: "Appoint tenant admin",
    adminEmail: "Email address",
    adminName: "Display name (for new users)",
    appoint: "Appoint",
    appointed: (email: string) => `${email} is now a tenant admin.`,
    domains: "Domain claims",
    domain: "Domain",
    tenant: "Tenant",
    ssoEnforced: "SSO enforced",
    claim: "Claim",
    release: "Release",
    created: (slug: string) => `Tenant "${slug}" created.`,
  },
  errors: {
    notFound: "Nicht gefunden.",
  },
} as const;
